# Shared by the IHP PDK setups, sourced by them (helpers from bootstrap.sh).
# shellcheck shell=bash

# ihp_osdi VA_DIR OUT_DIR MODEL...: compile each VA_DIR/<model>/<model>.va
# (psp103_nqs lives in psp103/) to OUT_DIR/<model>.osdi with the flags of
# IHP's own libs.tech/verilog-a/openvaf-compile-va.sh. Written to our own
# directory: the PDK's script writes into its tracked tree, which for
# SG13CMOS5L holds prebuilt Linux-only binaries.
ihp_osdi() {
  local va=$1 out=$2 m src; shift 2
  mkdir -p "$out"
  for m in "$@"; do
    case $m in psp103_nqs) src="$va/psp103/psp103_nqs.va" ;; *) src="$va/$m/$m.va" ;; esac
    compile_va "$src" "$out/$m.osdi" -D__NGSPICE__
  done
}

# ihp_glue PDK MODELS_DIR OSDI_DIR MODEL...: write ngspice/spiceinit (and a
# .spiceinit copy) loading each .osdi by absolute path, and example.sp.
ihp_glue() {
  local pdk=$1 models=$2 osdi=$3 m; shift 3
  local ng="$PREFIX/$pdk/ngspice"
  mkdir -p "$ng"
  {
    echo "* ngspice settings for $pdk (generated by bootstrap.sh). Copy to"
    echo "* ~/.spiceinit or to your simulation directory as .spiceinit."
    echo "* Same OSDI set as the PDK's own .spiceinit, with absolute paths"
    echo "* instead of \$PDK_ROOT/\$PDK."
    for m in "$@"; do echo "osdi '$osdi/$m.osdi'"; done
  } > "$ng/spiceinit"
  cp "$ng/spiceinit" "$ng/.spiceinit"
  render "$REPO/ngspice/ihp/example.sp.in" "$ng/example.sp" \
    "MODELS_DIR=$models" "NGSPICE=$NGSPICE" "PDK=$pdk"
}
